"""update_user

Revision ID: 4
Revises: 3
Create Date: 2026-01-07 02:32:30.104678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4'
down_revision: Union[str, Sequence[str], None] = '3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('father_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'father_name')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
